# Generated by Django 5.2.7 on 2025-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('warranty', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
    ]
