# Generated by Django 5.2.7 on 2025-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_bills_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='warranty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
