# Generated by Django 5.2.7 on 2025-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_bill_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='warranty',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
