# Generated by Django 5.2.7 on 2025-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_bill_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='warranty',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
